feat: realize json-visualizer with webpack
Ansagan-B/frontend-lab pull request #3
Opened 2021-09-06 16:20 UTC by Ansagan-B

2021-09-08 08:24 UTC, nastystanevich requested changes
As well add compression of files for production (use `gzip` and `brotliCompress` algoritms)

2021-09-08 08:24 UTC, nastystanevich commented on workflow/json-visualizer-webpack/webpack.config.js
> +        visualizer: './src/visualizer.js'
why do you create to entries?

2021-09-08 08:24 UTC, nastystanevich commented on workflow/json-visualizer-webpack/webpack.config.js
> +        library: 'webpackNumbers',
what is the `webpackNumbers` library?

2021-09-08 08:24 UTC, nastystanevich commented on workflow/json-visualizer-webpack/webpack.config.js
> +            },
for css use use `style-loader` but for scss `MiniCssExtractPlugin.loader`, why?

2021-09-08 10:20 UTC, Ansagan-B commented on workflow/json-visualizer-webpack/package.json
> +    "lodash": "^4.17.21",
ok, done!

2021-09-08 10:21 UTC, Ansagan-B commented on workflow/json-visualizer-webpack/dist/index.html
> +</body>
I will fix it

2021-09-09 09:24 UTC, nastystanevich approved these changes

2021-09-09 10:33 UTC, Ansagan-B commented on workflow/json-visualizer-webpack/src/visualizer.js
> +            if (str === 'null') {
_isNull has some issues with verification at this point

2021-09-09 10:33 UTC, merged