feat: implemented HTML page with switched tabs
Ansagan-B/frontend-lab pull request #6
Opened 2021-08-13 14:09 UTC by Ansagan-B

2021-08-18 10:17 UTC, nastystanevich requested changes

2021-08-18 10:17 UTC, nastystanevich commented on workflow/tabs/tabs-script.js
> +document.getElementById("1").classList.add('select');
1) you don't need this part, you can just call `selectTab` function when page was loaded. 
As well you can call this function without argument and set default `tabIndex` in the function (it will be used when argument is undefined),  about default values [you can read here](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Default_parameters).
2) change class name from `select` to `selected` (or smth else), because when we see name like `select` it means the item is select input, I think for our purpose adjective here is better.

2021-08-18 10:17 UTC, nastystanevich commented on workflow/tabs/tabs-script.js
> +    }
You can change this part to a little faster one: now you go thought all of items and remove classes, but there's some disadvantages here:
1) it's not dynamically, when you will want to add/remove tabs you should change not only in the `tabs` array but also here. 
2) js have to find 10 elements and try to remove classes in them, but in real we should remove classes only in 2.

Solution: find only items with `select` (`selected`) class name and remove class only in it.

2021-08-18 12:37 UTC, Ansagan-B commented on workflow/tabs/tabs-script.js
> +        tabindex: 'tabContent1'
changed to camel case.

2021-08-18 12:38 UTC, Ansagan-B commented on workflow/tabs/tabs-script.js
> +        title: "CSS", //название табы
thanks, removed.

2021-08-19 07:50 UTC, nastystanevich approved these changes

2021-08-19 07:58 UTC, merged